[2025-07-16T02:06:59.802-0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gdpr_ccpa_risk_pipeline.fetch_policy_data manual__2025-07-16T08:58:23.537815+00:00 [queued]>
[2025-07-16T02:06:59.806-0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gdpr_ccpa_risk_pipeline.fetch_policy_data manual__2025-07-16T08:58:23.537815+00:00 [queued]>
[2025-07-16T02:06:59.807-0700] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-07-16T02:06:59.822-0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): fetch_policy_data> on 2025-07-16 08:58:23.537815+00:00
[2025-07-16T02:06:59.838-0700] {standard_task_runner.py:57} INFO - Started process 85683 to run task
[2025-07-16T02:06:59.860-0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'gdpr_ccpa_risk_pipeline', 'fetch_policy_data', 'manual__2025-07-16T08:58:23.537815+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/gdpr_ccpa_risk_pipeline.py', '--cfg-path', '/var/folders/qv/gh2d3t7x7xqgkvbl149fblxr0000gn/T/tmp45lkhljx']
[2025-07-16T02:06:59.870-0700] {standard_task_runner.py:85} INFO - Job 8: Subtask fetch_policy_data
[2025-07-16T02:07:00.017-0700] {task_command.py:415} INFO - Running <TaskInstance: gdpr_ccpa_risk_pipeline.fetch_policy_data manual__2025-07-16T08:58:23.537815+00:00 [running]> on host amritas-macbook-pro.local
[2025-07-16T02:07:00.126-0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='gdpr_ccpa_risk_pipeline' AIRFLOW_CTX_TASK_ID='fetch_policy_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T08:58:23.537815+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-16T08:58:23.537815+00:00'
[2025-07-16T02:07:00.127-0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Volumes/Personal Drive/GitHub/gdpr-ccpa-risk-pipeline/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Personal Drive/GitHub/gdpr-ccpa-risk-pipeline/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Personal Drive/GitHub/gdpr-ccpa-risk-pipeline/dags/gdpr_ccpa_risk_pipeline.py", line 16, in fetch_policy
    from scripts.fetch_policy_data import fetch_policy_data
ModuleNotFoundError: No module named 'scripts'
[2025-07-16T02:07:00.142-0700] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gdpr_ccpa_risk_pipeline, task_id=fetch_policy_data, execution_date=20250716T085823, start_date=20250716T090659, end_date=20250716T090700
[2025-07-16T02:07:00.159-0700] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task fetch_policy_data (No module named 'scripts'; 85683)
[2025-07-16T02:07:00.189-0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-16T02:07:00.207-0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
