[2025-07-16T02:06:44.621-0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gdpr_ccpa_risk_pipeline.fetch_policy_data scheduled__2025-07-16T07:00:00+00:00 [queued]>
[2025-07-16T02:06:44.639-0700] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gdpr_ccpa_risk_pipeline.fetch_policy_data scheduled__2025-07-16T07:00:00+00:00 [queued]>
[2025-07-16T02:06:44.639-0700] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-07-16T02:06:44.715-0700] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): fetch_policy_data> on 2025-07-16 07:00:00+00:00
[2025-07-16T02:06:44.732-0700] {standard_task_runner.py:57} INFO - Started process 85672 to run task
[2025-07-16T02:06:44.777-0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'gdpr_ccpa_risk_pipeline', 'fetch_policy_data', 'scheduled__2025-07-16T07:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/gdpr_ccpa_risk_pipeline.py', '--cfg-path', '/var/folders/qv/gh2d3t7x7xqgkvbl149fblxr0000gn/T/tmp86q_am4t']
[2025-07-16T02:06:44.787-0700] {standard_task_runner.py:85} INFO - Job 6: Subtask fetch_policy_data
[2025-07-16T02:06:44.938-0700] {task_command.py:415} INFO - Running <TaskInstance: gdpr_ccpa_risk_pipeline.fetch_policy_data scheduled__2025-07-16T07:00:00+00:00 [running]> on host amritas-macbook-pro.local
[2025-07-16T02:06:45.021-0700] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='gdpr_ccpa_risk_pipeline' AIRFLOW_CTX_TASK_ID='fetch_policy_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T07:00:00+00:00'
[2025-07-16T02:06:45.024-0700] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Volumes/Personal Drive/GitHub/gdpr-ccpa-risk-pipeline/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Personal Drive/GitHub/gdpr-ccpa-risk-pipeline/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Personal Drive/GitHub/gdpr-ccpa-risk-pipeline/dags/gdpr_ccpa_risk_pipeline.py", line 16, in fetch_policy
    from scripts.fetch_policy_data import fetch_policy_data
ModuleNotFoundError: No module named 'scripts'
[2025-07-16T02:06:45.031-0700] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=gdpr_ccpa_risk_pipeline, task_id=fetch_policy_data, execution_date=20250716T070000, start_date=20250716T090644, end_date=20250716T090645
[2025-07-16T02:06:45.052-0700] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task fetch_policy_data (No module named 'scripts'; 85672)
[2025-07-16T02:06:45.122-0700] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-16T02:06:45.184-0700] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
